### ISSUE TITLE
Feature Request: Add Loop attribute

### ISSUE THREAD

**Issue by dotnetdreamer** [triniwiz/nativescript-pager#144] opened 2019-10-16 10:06 UTC
### Please, tell us how to recreate the issue in as much detail as possible. 
It would be nice to add a property on Pager e.g loop="true" which will loop the slider when reached to end.

**Comment by triniwiz** [comment] 2020-02-22 07:25
Duplicate of #125

**Closed by triniwiz** 2020-02-22 07:25 UTC
Labels: enhancement
