### ISSUE TITLE
[object Object], when set a variable of array type previously created in this.items

### ISSUE THREAD

**Issue by LauraNavarroGalvan** [triniwiz/nativescript-pager#71] opened 2018-06-13 16:33 UTC
When I have an array saved in the local storage, I get it and try to add it to this.items the view shows me [object Object], but when I console this.items it's fine.

```
let content = JSON.parse(localStorage.getItem('downloadedForms'));
this.items = new BehaviorSubject(content);
```
but works if I do the following 
```
let content = JSON.parse(localStorage.getItem('downloadedForms'));
this.http.get(environment.url_authentication + 'forms/' + id + '/prefered', { })
              .subscribe((result) => {
			this.items = new BehaviorSubject(content);
		}, (error) => {
			this.items = new BehaviorSubject(content);
		});
```

**Comment by triniwiz** [comment] 2018-12-02 08:56
Can you try the latest version :)

**Comment by triniwiz** [comment] 2018-12-08 19:32
Fixed in the latest

**Closed by triniwiz** 2018-12-08 19:32 UTC
Labels: bug

**Comment by wuilmerj24** [comment] 2020-07-22 05:23
@triniwiz In version 12.0.0-alpha.8 for angular the same thing happens. Use your demo-ng test example and it does the same.

**Comment by triniwiz** [comment] 2020-07-22 05:44
@wuilmerj24 try using an ObservableArray

**Comment by wuilmerj24** [comment] 2020-07-22 05:53
@triniwiz If that is what I am using.
`
private items:ObservableArray<any>;
 constructor(){
    this.items = new ObservableArray([
      {
        title: 'Slide 1',
        image: '~/images/Hulk_(comics_character).png'
      },
   ])
}
`

`<Pager row="0" [items]="items" #pager (selectedIndexChange)="onIndexChanged($event)" class="pager"
    backgroundColor="lightsteelblue">
    <ng-template let-item="item">
      <StackLayout>
        <Label [text]="item.title" textWrap="true"></Label>
      </StackLayout>
    </ng-template>
  </Pager>`

**Comment by wuilmerj24** [comment] 2020-07-22 06:55
@triniwiz  The problem is lazy loading. It already works correctly.

**Comment by triniwiz** [comment] 2020-07-22 07:58
Can you send a demo with the bug please I’ll dig into it
